[sdl]
fullscreen = false
windowresolution = 800x600
output = texture

[dosbox]
machine = svga_s3
memsize = 16

[cpu]
cpu_cycles = 12000

[mixer]
rate = 44100

[sblaster]
sbtype = sb16
sbbase = 220
irq = 7
dma = 1
hdma = 5

[autoexec]
@echo off
mount c game
mount d cdrom -t cdrom
c:
set dos4g=quiet
ADVENT -L0
exit
