[sdl]
fullscreen = false

[dosbox]
machine = svga_s3
memsize = 16

[cpu]
core = auto
cputype = 486_slow
cpu_cycles = 20000

[dos]
xms = true
ems = false
umb = true

[midi]
mididevice = none

[autoexec]
@echo off
mount c "/home/test/lutris_game_scripts_Regneslottet/extracted/Gys På Regneslottet/SYSTEM/DOSBOX/GAME"
imgmount d "/home/test/lutris_game_scripts_Regneslottet/extracted/Gys På Regneslottet/SYSTEM/DOSBOX/CDROM/CDROM.iso" -t iso
c:
cd windows
win c:\gilisoft\gys_cd\wnewaddd.exe /CFG:c:\gilisoft\gys_cd\wnewadd.ini /startdir:d:\dansk\
exit
