[sdl]
fullscreen=false
output=texture

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=auto
cputype=auto
cpu_cycles=12000

[mixer]
rate=44100
blocksize=1024
prebuffer=25

[midi]
mpu401=intelligent
mididevice=auto

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[autoexec]
@echo off
mount c "/home/test/lutris_game_scripts_yoejoe/game"
mount a "/home/test/lutris_game_scripts_yoejoe/Yo-Joe-Beat-the-Ghosts_DOS_EN" -t floppy
c:
cd \JOE
JOE.EXE
exit
